export const ELMT_TYPE = 'EM308'
export const ELMT_CODE_STRUCTPARTS = 'STRUCTPARTS' //结构部位
export const ELMT_CODE_CHECKTYPES = 'CHECKTYPES' //检验类别
export const ELMT_CODE_PIHAOS = 'PIHAOS' //炉、批号
export const ELMT_CODE_UNITNUMS = 'UNITNUMS' //生产厂家
export const ELMT_CODE_STANDNAMES = 'STANDNAMES' //检验标准
export const ELMT_CODE_EXPLS = 'EXPLS' //备注
export const ELMT_CODE_RECADDS = 'RECADDS' //取样地点
export const ELMT_CODE_SAMPNUMS = 'SAMPNUMS' // 样品编号
export const ELMT_CODE_SENDADDS = 'SENDADDS' //送样地点
export const ELMT_CODE_JBFSS = 'JBFSS' //搅拌方式
export const ELMT_CODE_KZS = 'KZS' //K值
export const ELMT_CODE_NJQDS = 'NJQDS' //粘结强度
export const ELMT_CODE_SJPZS = 'SJPZS' //砂浆品种
export const ELMT_CODE_CXFFS = 'CXFFS' //成型方法
export const ELMT_CODE_YHBZS = 'YHBZS' //养护条件
export const ELMT_CODE_KSXNS = 'KSXNS' //抗渗性能
export const ELMT_CODE_CDJS = 'CDJS' //强度等级
// export const ELMT_CODE_CBZCS = 'CBZCS' //标准差
export const ELMT_CODE_CCNOS = 'CCNOS' //水泥样品编号
export const ELMT_CODE_CVTYS = 'CVTYS' //水泥品种代号
export const ELMT_CODE_CCDJS = 'CCDJS' //水泥强度等级
// export const ELMT_CODE_CPQDS = 'CPQDS' //配置强度
export const ELMT_CODE_CPRODES = 'CPRODES' //水泥生产厂名
export const ELMT_CODE_CSAFTESS = 'CSAFTESS' //水泥安定性
export const ELMT_CODE_SZNUMS = 'SZNUMS' //骨料样品编号
export const ELMT_CODE_SZSVAS = 'SZSVAS' //骨料品种
export const ELMT_CODE_SZSPECS = 'SZSPECS' //骨料规格
export const ELMT_CODE_SZPRODES = 'SZPRODES' //骨料产地
export const ELMT_CODE_SZRIDS = 'SZRIDS' //骨料级配区
export const ELMT_CODE_SZNUM2S = 'SZNUM2S' //骨料样品编号2
export const ELMT_CODE_SZSVA2S = 'SZSVA2S' //骨料品种2
export const ELMT_CODE_SZSPEC2S = 'SZSPEC2S' //骨料规格2
export const ELMT_CODE_SZPRODE2S = 'SZPRODE2S' //骨料产地2
export const ELMT_CODE_SZRID2S = 'SZRID2S' //骨料级配区2
export const ELMT_CODE_MTPZS = 'MTPZS' //石灰膏品名
export const ELMT_CODE_MTPRODES = 'MTPRODES' //石灰膏产地
export const ELMT_CODE_CHPINZS = 'CHPINZS' //掺加料品种
export const ELMT_CODE_MTDJS = 'MTDJS' //掺加料等级
export const ELMT_CODE_MTSYFHS = 'MTSYFHS' //掺加料掺入方式
export const ELMT_CODE_CHPRODES = 'CHPRODES' //掺加料生产厂家
export const ELMT_CODE_WJNOS = 'WJNOS' //外加剂样品编号
export const ELMT_CODE_WJPZS = 'WJPZS' //外加剂品种
export const ELMT_CODE_WJPMS = 'WJPMS' //外加剂品名
export const ELMT_CODE_WJPRODES = 'WJPRODES' //生产厂家
export const ELMT_CODE_MTWATERS = 'MTWATERS' //水源
export const ELMT_CODE_OUTNUBS = 'OUTNUBS' //水泥出厂编号
