export const ELMT_TYPE = 'EM303'
export const ELMT_CODE_STRUCTPARTS = 'STRUCTPARTS' //结构部位
export const ELMT_CODE_CHECKTYPES = 'CHECKTYPES' //检验类别
export const ELMT_CODE_PIHAOS = 'PIHAOS' //批号
export const ELMT_CODE_UNITNUMS = 'UNITNUMS' //生产厂家
export const ELMT_CODE_EXPLS = 'EXPLS' //备注
export const ELMT_CODE_HG_CODES = 'HG_CODES' //合格证号
export const ELMT_CODE_RECADDS = 'RECADDS' //取样地点
export const ELMT_CODE_VOL1S = 'VOL1S' //经销单位
export const ELMT_CODE_VOL2S = 'VOL2S' //实测直径1
export const ELMT_CODE_VOL3S = 'VOL3S' //实测直径2
export const ELMT_CODE_SENDADDS = 'SENDADDS' //送样地点
export const ELMT_CODE_SAMPNAMES = 'SAMPNAMES' // 样品名称
export const ELMT_CODE_JGZTS = 'JGZT' // 加工状态
export const ELMT_CODE_TESTBATCHS = 'TESTBATCH' // 检验批号
