export const ELMT_TYPE = 'EM302'
export const ELMT_CODE_STRUCTPARTS = 'STRUCTPARTS' //结构部位
export const ELMT_CODE_CHECKTYPES = 'CHECKTYPES' //检验类别
export const ELMT_CODE_PIHAOS = 'PIHAOS' //炉、批号
export const ELMT_CODE_UNITNUMS = 'UNITNUMS' //生产厂家
export const ELMT_CODE_EXPLS = 'EXPLS' //备注
export const ELMT_CODE_RECADDS = 'RECADDS' //取样地点
export const ELMT_CODE_PAIHAOS = 'PAIHAOS' // 牌号
export const ELMT_CODE_SAMPNUMS = 'SAMPNUMS' // 样品编号
export const ELMT_CODE_SENDADDS = 'SENDADDS' //送样地点
export const ELMT_CODE_GJJB = 'GJJBS' //接头等级
export const ELMT_CODE_CHECKFRM = 'CHECKFRMS' // 检验形式
export const ELMT_CODE_JTLX = 'JTLXS' // 接头类型
export const ELMT_CODE_SAMPNAMES = 'SAMPNAMES' // 样品名称
