export const ELMT_TYPE = 'EM306'
export const ELMT_CODE_STRUCTPARTS = 'STRUCTPARTS' //结构部位
export const ELMT_CODE_CHECKTYPES = 'CHECKTYPES' //检验类别
export const ELMT_CODE_UNITNUMS = 'UNITNUMS' //生产厂家
export const ELMT_CODE_STANDNAMES = 'STANDNAMES' //检验标准
export const ELMT_CODE_EXPLS = 'EXPLS' //备注
export const ELMT_CODE_RECADDS = 'RECADDS' //取样地点
export const ELMT_CODE_PAIHAOS = 'PAIHAOS' // 牌号
export const ELMT_CODE_SAMPNUMS = 'SAMPNUMS' // 样品编号
export const ELMT_CODE_JIANYANPIHAO = 'JIANYANPIHAO' //检验批号
export const ELMT_CODE_QDDJC = 'QDDJC' //强度等级C
export const ELMT_CODE_LINGQI = 'LINGQI' //要求龄期
export const ELMT_CODE_CEMENTTYPE = 'CEMENTTYPE' //水泥品种
export const ELMT_CODE_PHBBH = 'PHBBH' //配合比编号
export const ELMT_CODE_YHTJ = 'YHTJ' //养护条件
export const ELMT_CODE_PHB = 'PHB' //配合比
export const ELMT_CODE_YPCC = 'YPCC' //样品尺寸
export const ELMT_CODE_SNB = 'SNB' //水灰比
export const ELMT_CODE_KSDJ = 'KSDJ' //抗渗等级
export const ELMT_CODE_SNBH = 'SNBH' //水泥标号
export const ELMT_CODE_SNYL = 'SNYL' //水泥用量
export const ELMT_CODE_SHALV = 'SHALV' //砂率
export const ELMT_CODE_ADDITIVE1 = 'ADDITIVE1' //外加剂种类1
export const ELMT_CODE_ADDITIVE2 = 'ADDITIVE2' //外加剂种类2
export const ELMT_CODE_ADDITIVE3 = 'ADDITIVE3' //外加剂种类3
export const ELMT_CODE_PRODUNIT = 'PRODUNIT' //生产单位
export const ELMT_CODE_JCBZ = 'JCBZ' // 检测标准
export const ELMT_CODE_SAMPNAMES = 'SAMPNAMES' // 样品名称
